[tool.poetry]
name = "monodb"
version = "0.0.1"
description = ""
authors = ["nulocat <nulocat@proton.me>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
